-- MySQL Script generated by MySQL Workbench
-- Thu Jan 21 14:28:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.` annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` annonce` (
  `id_annonce` INT NOT NULL,
  `titre` VARCHAR(255) NULL,
  `description` TEXT(1500) NULL,
  `photo` VARCHAR(255) NULL,
  `nationalite` VARCHAR(255) NULL,
  `annonce_date` DATE NULL,
  `id_user` INT NOT NULL,
  ` annonce_pdf` VARCHAR(255) NULL,
  PRIMARY KEY (`id_annonce`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  ` annonce_id_annonce` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_ annonce_idx` (` annonce_id_annonce` ASC) VISIBLE,
  CONSTRAINT `fk_user_ annonce`
    FOREIGN KEY (` annonce_id_annonce`)
    REFERENCES `mydb`.` annonce` (`id_annonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
